### PR TITLE
feat: add protoc-gen-go-grpc

### PR DESCRIPTION
**Pull request by AlekSi**
See https://github.com/golang/protobuf/issues/1070

Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@gmail.com>

### CODE REVIEW

**Review by smira — COMMENTED** [review]
we should copy the built image into the `tools` image (add it as dependency)

**Review by andrewrynhard — APPROVED** [review]
Thanks @AlekSi!

**Comment by smira** [comment]
> we should copy the built image into the `tools` image (add it as dependency)

here: https://github.com/talos-systems/tools/blob/master/tools/pkg.yaml#L4

**Comment by AlekSi** [comment]
@smira Done

**Review by smira — APPROVED** [review]
thank you!

**Comment by AlekSi** [comment]
Fixed typo

**Comment by smira** [comment]
```
#881 linux/amd64 protoc-gen-go-grpc:build-0
#881 0.082 /bin/sh: line 3: cd: cmd/protoc-gen-go-grpc-grpc: No such file or directory
#881 ERROR: executor failed running [/bin/sh -c set -eou pipefail
export PATH=${TOOLCHAIN}/go/bin:${PATH}
export GO111MODULE=on
cd cmd/protoc-gen-go-grpc-grpc
go build .
]: exit code: 1
```

**Comment by AlekSi** [comment]
Yeah, _that_ typo :)

**Comment by AlekSi** [comment]
@smira CI passed

**Pull request merged**
