### PR TITLE
chore: update bldr with new version

### PR DESCRIPTION
**Pull request by smira**
This pulls in optimized flow and also bumps alpine to 3.14.

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

### CODE REVIEW

**Comment by smira** [comment]
image

much better than 30 mins on avg before the change

**Comment by smira** [comment]
I manually tested that this bump in `alpine` doesn't break the build of `pkgs` with the new `tools`

**Review by AlekSi — APPROVED** [review]
:shipit:

**Pull request merged**
